<template>
  <v-container class="mt-4">
    <v-card rounded="lg" color="grey-darken-4" class="d-flfex align-end">
      <div
        v-for="(imgGroup, index) in productImg"
        :key="index"
        style="overflow: hidden">
        <div
          class="d-flex justify-space-around py-2"
          :class="`img-group-${index}`">
          <img
            v-for="imgUrl in imgGroup"
            :key="imgUrl"
            :src="imgUrl"
            alt="nft-product"
            class="nft-product"
            width="75"
            height="75" />
        </div>
        <v-card
          v-if="index === 1"
          rounded="lg"
          color="grey-darken-4"
          class="d-flex align-end justify-space-between font-italic px-4 pb-2 my-2"
          style="font-size: 14px">
          <div>
            <div>test</div>
            <div class="total-size">{{ t("home.totalRevenue") }}</div>
          </div>
          <div class="mt-2">
            <div>321321</div>
            <div class="total-size">{{ t("home.userRevenue") }}</div>
          </div>
          <div class="mt-2">
            <div>123123</div>
            <div class="total-size">{{ t("home.participant") }}</div>
          </div>
        </v-card>
      </div>
    </v-card>
  </v-container>
</template>
<script>
import { useI18n } from "vue-i18n";

export default {
  setup() {
    const { t, locale } = useI18n();
    return {
      t,
      locale,
    };
  },
  data() {
    return {
      productCarousel: [],
      productImg: [
        [
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
        ],
        [
          "NFT/1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/2.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
          "NFT/1.jpeg",
          "NFT/2-1.jpeg",
          "NFT/2-2.jpeg",
          "NFT/2-3.jpeg",
        ],
        [
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/3.jpeg",
          "NFT/3-1.jpeg",
          "NFT/3-2.jpeg",
          "NFT/3-3.jpeg",
        ],
        [
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
          "NFT/4.jpeg",
          "NFT/4-1.jpeg",
          "NFT/4-2.jpeg",
          "NFT/4-3.jpeg",
          "NFT/1-1.jpeg",
          "NFT/1-2.jpeg",
          "NFT/1-3.jpeg",
          "NFT/1-4.jpeg",
        ],
      ],
      // items: [
      //   {
      //     title: "home.title-1",
      //     description: "home.text-1",
      //     image: "./home-1.gif",
      //   },
      //   {
      //     title: "home.title-2",
      //     description: "home.text-2",
      //     image: "./home-2.gif",
      //   },
      //   {
      //     title: "home.title-3",
      //     description: "home.text-3",
      //     image: "./home-3.gif",
      //   },
      // ],

      websiteIntroHtml: "",
      balance_total: 0,
      income_total: 0,
      user_total: 0,
    };
  },
};
</script>
<style>
.nft-product {
  margin: 0 3px;
  max-height: 5vmax;
  border-radius: 6px;
}
.total-size {
  font: size 12px;
}

.img-group-0 {
  animation: traveling 80s linear infinite;
}
.img-group-1 {
  animation: traveling 40s linear infinite;
}
.img-group-2 {
  animation: traveling 50s linear reverse infinite;
}
.img-group-3 {
  animation: traveling 70s linear reverse infinite;
}
</style>
